services:
  # Backend API
  server:
    image: thunder9596/financial-chatbot-backend:latest
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    depends_on:
      - redis
      - rabbitmq
      - chromadb
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000

  # Frontend
  frontend:
    image: thunder9596/financial-chatbot-frontend:latest
    ports:
      - "5173:5173"
    restart: always
    environment:
      - VITE_API_URL=http://54.252.9.137:8000

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Celery Worker
  celery_worker:
    image: thunder9596/financial-chatbot-backend:latest
    command: celery -A app.celery_app worker --loglevel=info
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - server
      - chromadb
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000
      - HF_HOME=/app/hf_cache

  # ChromaDB
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - chroma_data:/chroma/chroma

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  redis_data:
  rabbitmq_data:
  chroma_data: